import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';

type Language = 'pt' | 'en' | 'es' | 'fr' | 'de' | 'it' | 'zh' | 'ja' | 'ko' | 'ru' | 'ar' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navigation
    'nav.features': 'Recursos',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'auth.login': 'Login',
    'auth.signup': 'Cadastrar',
    'auth.logout': 'Sair',
    'nav.dashboard': 'Dashboard',
    
    // Hero Section
    'hero.badge': 'Orientação Profissional com IA',
    'hero.title': 'Sua jornada para o',
    'hero.titleHighlight': ' mercado de trabalho ',
    'hero.titleEnd': 'começa aqui',
    'hero.description': 'O NexusAI é seu assistente inteligente para encontrar oportunidades, aprimorar seu currículo e conquistar a vaga dos seus sonhos.',
    'hero.getStarted': 'Começar Agora',
    'hero.demo': 'Ver Demonstração',
    'hero.stat1': 'Jovens Orientados',
    'hero.stat2': 'Taxa de Sucesso',
    'hero.stat3': 'Suporte IA',
    
    // Features Section
    'features.title': 'Recursos que',
    'features.titleHighlight': ' Transformam',
    'features.titleEnd': ' Carreiras',
    'features.subtitle': 'Descubra como nossa inteligência artificial pode acelerar sua entrada no mercado de trabalho',
    'features.resume.title': 'Otimização de Currículo',
    'features.resume.desc': 'IA analisa e otimiza seu currículo para cada vaga específica, destacando suas melhores qualidades.',
    'features.resume.action': 'Otimizar Currículo',
    'features.interview.title': 'Preparação para Entrevistas',
    'features.interview.desc': 'Simulações de entrevistas personalizadas com feedback inteligente para você se destacar.',
    'features.interview.action': 'Treinar Entrevistas',
    'features.jobs.title': 'Busca Inteligente de Vagas',
    'features.jobs.desc': 'Encontre oportunidades perfeitas com base no seu perfil, experiência e objetivos profissionais.',
    'features.jobs.action': 'Buscar Vagas',
    'features.skills.title': 'Desenvolvimento de Habilidades',
    'features.skills.desc': 'Identifique gaps de competências e receba um plano personalizado de capacitação.',
    'features.skills.action': 'Desenvolver Skills',
    'features.networking.title': 'Networking Estratégico',
    'features.networking.desc': 'Conecte-se com profissionais da sua área e expanda sua rede de contatos.',
    'features.networking.action': 'Fazer Networking',
    'features.mentoring.title': 'Orientação Personalizada',
    'features.mentoring.desc': 'Mentoria 24/7 com IA que entende seus objetivos e traça o melhor caminho profissional.',
    'features.mentoring.action': 'Obter Orientação',
    'features.cta': 'Experimentar Todos os Recursos',
    
    // About Section
    'about.title': 'Por que escolher o',
    'about.titleHighlight': ' NexusAI',
    'about.subtitle': 'Desenvolvemos uma plataforma pensada especificamente para jovens brasileiros que estão dando os primeiros passos no mercado de trabalho.',
    'about.data.title': 'Orientação Baseada em Dados',
    'about.data.desc': 'Nossa IA analisa milhares de vagas e perfis profissionais para oferecer conselhos precisos e atualizados com o mercado.',
    'about.focus.title': 'Foco no Primeiro Emprego',
    'about.focus.desc': 'Entendemos os desafios únicos de quem está começando e adaptamos nossas estratégias para superar essas barreiras.',
    'about.learning.title': 'Aprendizado Contínuo',
    'about.learning.desc': 'Acompanhe as tendências do mercado e desenvolva as habilidades mais requisitadas pelos empregadores.',
    'about.support.title': 'Suporte Humanizado',
    'about.support.desc': 'Tecnologia avançada com toque humano. Nossa IA é treinada para ser empática e compreender suas necessidades individuais.',
    'about.stat1': 'Currículos otimizados',
    'about.stat2': 'Taxa de aprovação em processos',
    'about.cta': 'Comece Sua Jornada Profissional',
    
    // Contact Section
    'contact.title': 'Entre em',
    'contact.titleHighlight': ' Contato',
    'contact.subtitle': 'Tem alguma dúvida ou precisa de ajuda? Nossa equipe está pronta para te orientar!',
    'contact.info': 'Fale Conosco',
    'contact.email': 'E-mail',
    'contact.phone': 'Telefone',
    'contact.address': 'Endereço',
    'contact.form.title': 'Envie uma Mensagem',
    'contact.form.name': 'Nome',
    'contact.form.namePlaceholder': 'Seu nome',
    'contact.form.email': 'E-mail',
    'contact.form.emailPlaceholder': 'seu@email.com',
    'contact.form.subject': 'Assunto',
    'contact.form.subjectPlaceholder': 'Como podemos te ajudar?',
    'contact.form.message': 'Mensagem',
    'contact.form.messagePlaceholder': 'Descreva sua dúvida ou sugestão...',
    'contact.form.submit': 'Enviar Mensagem',
    
    // Dashboard
    'dashboard.title': 'Painel de Controle',
    'dashboard.welcome': 'Bem-vindo de volta',
    'dashboard.welcomeBack': 'Bem-vindo de volta',
    'dashboard.resume': 'Otimizar Currículo',
    'dashboard.resumeDesc': 'Crie e otimize seu currículo profissional',
    'dashboard.interview': 'Preparação para Entrevistas',
    'dashboard.interviewDesc': 'Pratique e prepare-se para suas entrevistas',
    'dashboard.skills': 'Desenvolvimento de Habilidades',
    'dashboard.skillsDesc': 'Aprimore suas competências profissionais',
    'dashboard.jobs': 'Buscar Vagas',
    'dashboard.jobsDesc': 'Encontre oportunidades de emprego',
    'dashboard.backHome': 'Voltar para Início',
    'dashboard.home': 'Início',
    'dashboard.settings': 'Configurações',
    'dashboard.admin': 'Painel Admin',
    'dashboard.errorProfile': 'Erro ao carregar perfil',
    'dashboard.errorPermissions': 'Erro ao verificar permissões',
    'dashboard.quickActions': 'Ações Rápidas',
    'dashboard.recentActivity': 'Atividade Recente',
    'dashboard.recommendations': 'Recomendações para Você',
    'dashboard.profileStrength': 'Força do Perfil',
    'dashboard.aiInsights': 'Insights de IA',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.description': 'Gerencie suas preferências e informações pessoais',
    'settings.profileCompletion': 'Conclusão do Perfil',
    'settings.completeYourProfile': 'Complete seu perfil para melhorar sua experiência',
    'settings.complete': 'completo',
    'settings.fields': 'campos',
    'settings.suggestions': 'Sugestões',
    'settings.add': 'Adicionar',
    'settings.careerField': 'Área de Atuação',
    'settings.experienceLevel': 'Nível de Experiência',
    'settings.avatarUrl': 'Foto de Perfil',
    'settings.profile': 'Perfil',
    'settings.notifications': 'Notificações',
    'settings.privacy': 'Privacidade',
    'settings.security': 'Segurança',
    'settings.appearance': 'Aparência',
    'settings.personalInfo': 'Informações Pessoais',
    'settings.fullName': 'Nome Completo',
    'settings.email': 'E-mail',
    'settings.phone': 'Telefone',
    'settings.bio': 'Biografia',
    'settings.bioPlaceholder': 'Conte um pouco sobre você...',
    'settings.saveProfile': 'Salvar Perfil',
    'settings.profileUpdated': 'Perfil atualizado!',
    'settings.profileUpdateDesc': 'Suas informações foram salvas com sucesso.',
    'settings.notificationPrefs': 'Preferências de Notificação',
    'settings.emailNotifications': 'Notificações por E-mail',
    'settings.emailNotificationsDesc': 'Receba notificações importantes por e-mail',
    'settings.pushNotifications': 'Notificações Push',
    'settings.pushNotificationsDesc': 'Receba notificações em tempo real',
    'settings.weeklyReport': 'Relatório Semanal',
    'settings.weeklyReportDesc': 'Receba um resumo das suas atividades',
    'settings.courseUpdates': 'Atualizações de Cursos',
    'settings.courseUpdatesDesc': 'Novos cursos e materiais disponíveis',
    'settings.saveNotifications': 'Salvar Notificações',
    'settings.notificationsSaved': 'Preferências salvas!',
    'settings.notificationsSavedDesc': 'Suas configurações de notificação foram atualizadas.',
    'settings.privacySettings': 'Configurações de Privacidade',
    'settings.profileVisibility': 'Visibilidade do Perfil',
    'settings.public': 'Público',
    'settings.private': 'Privado',
    'settings.showEmail': 'Mostrar E-mail',
    'settings.showEmailDesc': 'Seu e-mail será visível no perfil',
    'settings.showPhone': 'Mostrar Telefone',
    'settings.showPhoneDesc': 'Seu telefone será visível no perfil',
    'settings.savePrivacy': 'Salvar Privacidade',
    'settings.privacyUpdated': 'Privacidade atualizada!',
    'settings.privacyUpdatedDesc': 'Suas configurações de privacidade foram salvas.',
    'settings.twoFactor': 'Autenticação em Dois Fatores (2FA)',
    'settings.twoFactorDesc': 'Adicione uma camada extra de segurança à sua conta',
    'settings.twoFactorEnabled': '2FA está ativado',
    'settings.twoFactorDisabled': '2FA está desativado',
    'settings.enable2FA': 'Ativar 2FA',
    'settings.disable2FA': 'Desativar 2FA',
    'settings.2FADisabled': '2FA Desativado',
    'settings.2FADisabledDesc': 'Autenticação em dois fatores foi desativada',
    'settings.error2FA': 'Falha ao desativar 2FA',
    'settings.themeSettings': 'Configurações de Tema',
    'settings.currentTheme': 'Tema Atual',
    'settings.themeToggle': 'Alternar Tema',
    
    // User Profile
    'profile.dashboard': 'Dashboard',
    'profile.settings': 'Configurações',
    'profile.logout': 'Sair',
    'profile.professional': 'Profissional',
    
    // Admin Panel
    'admin.title': 'Painel de Administração',
    'admin.description': 'Gerencie usuários e permissões',
    'admin.authSettings': 'Configurações de Autenticação',
    'admin.authSettingsDesc': 'Gerencie configurações de autenticação e registro',
    'admin.requireEmailConfirmation': 'Exigir confirmação de e-mail',
    'admin.emailConfirmationDesc': 'Usuários precisam confirmar o e-mail antes de fazer login (desative para testes)',
    'admin.settingsSaved': 'Configurações salvas',
    'admin.emailConfirmationEnabled': 'Confirmação de e-mail habilitada',
    'admin.emailConfirmationDisabled': 'Confirmação de e-mail desabilitada (modo de desenvolvimento)',
    'admin.error': 'Erro',
    'admin.errorSavingSettings': 'Erro ao salvar configurações',
    'admin.allUsers': 'Todos os Usuários',
    'admin.name': 'Nome',
    'admin.email': 'E-mail',
    'admin.role': 'Função',
    'admin.createdAt': 'Criado em',
    'admin.actions': 'Ações',
    'admin.noUsers': 'Nenhum usuário encontrado',
    'admin.deleteUser': 'Excluir Usuário',
    'admin.deleteConfirm': 'Tem certeza que deseja excluir este usuário?',
    'admin.deleteDesc': 'Esta ação não pode ser desfeita.',
    'admin.cancel': 'Cancelar',
    'admin.delete': 'Excluir',
    'admin.userDeleted': 'Usuário excluído',
    'admin.userDeletedDesc': 'O usuário foi removido com sucesso',
    'admin.errorDelete': 'Erro ao excluir usuário',
    'admin.errorFetch': 'Erro ao carregar usuários',
    'admin.admin': 'Admin',
    'admin.client': 'Cliente',
    
    // Demo Page
    'demo.title': 'NexusAI Demo',
    'demo.hero': 'Explore o Poder da',
    'demo.heroHighlight': ' IA ',
    'demo.heroEnd': 'no seu desenvolvimento profissional',
    'demo.heroDesc': 'Veja demonstrações interativas de como o NexusAI pode transformar sua carreira',
    'demo.watchDemo': 'Assistir Demo',
    'demo.howItWorks': 'Como Funciona',
    'demo.stepByStep': 'Passo a passo do processo',
    'demo.testimonials': 'O que nossos usuários dizem',
    'demo.cta.title': 'Pronto para transformar sua carreira?',
    'demo.cta.desc': 'Junte-se a milhares de profissionais que já estão usando o NexusAI',
    'demo.cta.start': 'Começar Gratuitamente',
    'demo.cta.learn': 'Saber Mais',
    'demo.resume.title': 'Otimização de Currículo',
    'demo.resume.desc': 'Veja como a IA analisa e melhora seu currículo em tempo real',
    'demo.resume.step1': 'Upload do seu currículo atual',
    'demo.resume.step2': 'Análise automática de pontos fortes e fracos',
    'demo.resume.step3': 'Sugestões de melhorias baseadas em IA',
    'demo.resume.step4': 'Geração de currículo otimizado em PDF',
    'demo.resume.stat1': 'Aumento médio na taxa de resposta',
    'demo.resume.stat2': 'Tempo médio de otimização',
    'demo.resume.stat3': 'Currículos otimizados',
    'demo.interview.title': 'Preparação para Entrevistas',
    'demo.interview.desc': 'Pratique com simulações realistas de entrevistas',
    'demo.interview.step1': 'Escolha o tipo de vaga desejada',
    'demo.interview.step2': 'Receba perguntas personalizadas',
    'demo.interview.step3': 'Grave suas respostas em tempo real',
    'demo.interview.step4': 'Obtenha feedback detalhado da IA',
    'demo.interview.stat1': 'Taxa de aprovação após treino',
    'demo.interview.stat2': 'Perguntas disponíveis',
    'demo.interview.stat3': 'Feedback personalizado',
    'demo.skills.title': 'Desenvolvimento de Habilidades',
    'demo.skills.desc': 'Aprimore suas competências com trilhas personalizadas',
    'demo.skills.step1': 'Avaliação inicial de competências',
    'demo.skills.step2': 'Trilha de aprendizado personalizada',
    'demo.skills.step3': 'Exercícios práticos e desafios',
    'demo.skills.step4': 'Certificados de conclusão',
    'demo.skills.stat1': 'Habilidades disponíveis',
    'demo.skills.stat2': 'Tempo médio de conclusão',
    'demo.skills.stat3': 'Taxa de satisfação',
  },
  en: {
    'nav.features': 'Features',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Logout',
    'nav.dashboard': 'Dashboard',
    'hero.badge': 'AI-Powered Career Guidance',
    'hero.title': 'Your journey to the',
    'hero.titleHighlight': ' job market ',
    'hero.titleEnd': 'starts here',
    'hero.description': 'NexusAI is your intelligent assistant to find opportunities, improve your resume and land your dream job.',
    'hero.getStarted': 'Get Started',
    'hero.demo': 'View Demo',
    'hero.stat1': 'Guided Youth',
    'hero.stat2': 'Success Rate',
    'hero.stat3': 'AI Support',
    'features.title': 'Resources that',
    'features.titleHighlight': ' Transform',
    'features.titleEnd': ' Careers',
    'features.subtitle': 'Discover how our artificial intelligence can accelerate your entry into the job market',
    'features.resume.title': 'Resume Optimization',
    'features.resume.desc': 'AI analyzes and optimizes your resume for each specific job, highlighting your best qualities.',
    'features.resume.action': 'Optimize Resume',
    'features.interview.title': 'Interview Preparation',
    'features.interview.desc': 'Personalized interview simulations with intelligent feedback to help you stand out.',
    'features.interview.action': 'Train Interviews',
    'features.jobs.title': 'Smart Job Search',
    'features.jobs.desc': 'Find perfect opportunities based on your profile, experience and professional goals.',
    'features.jobs.action': 'Search Jobs',
    'features.skills.title': 'Skills Development',
    'features.skills.desc': 'Identify skill gaps and receive a personalized training plan.',
    'features.skills.action': 'Develop Skills',
    'features.networking.title': 'Strategic Networking',
    'features.networking.desc': 'Connect with professionals in your field and expand your network.',
    'features.networking.action': 'Network',
    'features.mentoring.title': 'Personalized Guidance',
    'features.mentoring.desc': '24/7 AI mentorship that understands your goals and maps out the best professional path.',
    'features.mentoring.action': 'Get Guidance',
    'features.cta': 'Try All Features',
    'about.title': 'Why choose',
    'about.titleHighlight': ' NexusAI',
    'about.subtitle': 'We developed a platform specifically designed for young Brazilians taking their first steps in the job market.',
    'about.data.title': 'Data-Driven Guidance',
    'about.data.desc': 'Our AI analyzes thousands of job postings and professional profiles to offer accurate and up-to-date advice.',
    'about.focus.title': 'Focus on First Job',
    'about.focus.desc': 'We understand the unique challenges of those starting out and adapt our strategies to overcome these barriers.',
    'about.learning.title': 'Continuous Learning',
    'about.learning.desc': 'Keep up with market trends and develop the most sought-after skills by employers.',
    'about.support.title': 'Humanized Support',
    'about.support.desc': 'Advanced technology with a human touch. Our AI is trained to be empathetic and understand your individual needs.',
    'about.stat1': 'Optimized resumes',
    'about.stat2': 'Approval rate in processes',
    'about.cta': 'Start Your Professional Journey',
    'contact.title': 'Get in',
    'contact.titleHighlight': ' Touch',
    'contact.subtitle': 'Have a question or need help? Our team is ready to guide you!',
    'contact.info': 'Contact Us',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.address': 'Address',
    'contact.form.title': 'Send a Message',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Your name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'How can we help you?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Describe your question or suggestion...',
    'contact.form.submit': 'Send Message',
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.welcomeBack': 'Welcome back',
    'dashboard.resume': 'Resume Optimizer',
    'dashboard.resumeDesc': 'Create and optimize your professional resume',
    'dashboard.interview': 'Interview Preparation',
    'dashboard.interviewDesc': 'Practice and prepare for your interviews',
    'dashboard.skills': 'Skills Development',
    'dashboard.skillsDesc': 'Enhance your professional competencies',
    'dashboard.jobs': 'Job Search',
    'dashboard.jobsDesc': 'Find job opportunities',
    'dashboard.backHome': 'Back to Home',
    'dashboard.home': 'Home',
    'dashboard.settings': 'Settings',
    'dashboard.admin': 'Admin Panel',
    'dashboard.errorProfile': 'Error loading profile',
    'dashboard.errorPermissions': 'Error checking permissions',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.recommendations': 'Recommendations for You',
    'dashboard.profileStrength': 'Profile Strength',
    'dashboard.aiInsights': 'AI Insights',
    'settings.title': 'Settings',
    'settings.description': 'Manage your preferences and personal information',
    'settings.profileCompletion': 'Profile Completion',
    'settings.completeYourProfile': 'Complete your profile to improve your experience',
    'settings.complete': 'complete',
    'settings.fields': 'fields',
    'settings.suggestions': 'Suggestions',
    'settings.add': 'Add',
    'settings.careerField': 'Career Field',
    'settings.experienceLevel': 'Experience Level',
    'settings.avatarUrl': 'Profile Picture',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.security': 'Security',
    'settings.appearance': 'Appearance',
    'settings.personalInfo': 'Personal Information',
    'settings.fullName': 'Full Name',
    'settings.email': 'Email',
    'settings.phone': 'Phone',
    'settings.bio': 'Bio',
    'settings.bioPlaceholder': 'Tell us about yourself...',
    'settings.saveProfile': 'Save Profile',
    'settings.profileUpdated': 'Profile updated!',
    'settings.profileUpdateDesc': 'Your information has been saved successfully.',
    'settings.notificationPrefs': 'Notification Preferences',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive important notifications via email',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsDesc': 'Receive real-time notifications',
    'settings.weeklyReport': 'Weekly Report',
    'settings.weeklyReportDesc': 'Receive a summary of your activities',
    'settings.courseUpdates': 'Course Updates',
    'settings.courseUpdatesDesc': 'New courses and materials available',
    'settings.saveNotifications': 'Save Notifications',
    'settings.notificationsSaved': 'Preferences saved!',
    'settings.notificationsSavedDesc': 'Your notification settings have been updated.',
    'settings.privacySettings': 'Privacy Settings',
    'settings.profileVisibility': 'Profile Visibility',
    'settings.public': 'Public',
    'settings.private': 'Private',
    'settings.showEmail': 'Show Email',
    'settings.showEmailDesc': 'Your email will be visible on your profile',
    'settings.showPhone': 'Show Phone',
    'settings.showPhoneDesc': 'Your phone will be visible on your profile',
    'settings.savePrivacy': 'Save Privacy',
    'settings.privacyUpdated': 'Privacy updated!',
    'settings.privacyUpdatedDesc': 'Your privacy settings have been saved.',
    'settings.twoFactor': 'Two-Factor Authentication (2FA)',
    'settings.twoFactorDesc': 'Add an extra layer of security to your account',
    'settings.twoFactorEnabled': '2FA is enabled',
    'settings.twoFactorDisabled': '2FA is disabled',
    'settings.enable2FA': 'Enable 2FA',
    'settings.disable2FA': 'Disable 2FA',
    'settings.2FADisabled': '2FA Disabled',
    'settings.2FADisabledDesc': 'Two-factor authentication has been disabled',
    'settings.error2FA': 'Failed to disable 2FA',
    'settings.themeSettings': 'Theme Settings',
    'settings.currentTheme': 'Current Theme',
    'settings.themeToggle': 'Toggle Theme',
    'profile.dashboard': 'Dashboard',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',
    'profile.professional': 'Professional',
    'admin.title': 'Administration Panel',
    'admin.description': 'Manage users and permissions',
    'admin.authSettings': 'Authentication Settings',
    'admin.authSettingsDesc': 'Manage authentication and registration settings',
    'admin.requireEmailConfirmation': 'Require email confirmation',
    'admin.emailConfirmationDesc': 'Users must confirm email before logging in (disable for testing)',
    'admin.settingsSaved': 'Settings saved',
    'admin.emailConfirmationEnabled': 'Email confirmation enabled',
    'admin.emailConfirmationDisabled': 'Email confirmation disabled (development mode)',
    'admin.error': 'Error',
    'admin.errorSavingSettings': 'Error saving settings',
    'admin.allUsers': 'All Users',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.createdAt': 'Created at',
    'admin.actions': 'Actions',
    'admin.noUsers': 'No users found',
    'admin.deleteUser': 'Delete User',
    'admin.deleteConfirm': 'Are you sure you want to delete this user?',
    'admin.deleteDesc': 'This action cannot be undone.',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.userDeleted': 'User deleted',
    'admin.userDeletedDesc': 'User has been removed successfully',
    'admin.errorDelete': 'Error deleting user',
    'admin.errorFetch': 'Error loading users',
    'admin.admin': 'Admin',
    'admin.client': 'Client',
    'demo.title': 'NexusAI Demo',
    'demo.hero': 'Explore the Power of',
    'demo.heroHighlight': ' AI ',
    'demo.heroEnd': 'in your professional development',
    'demo.heroDesc': 'See interactive demonstrations of how NexusAI can transform your career',
    'demo.watchDemo': 'Watch Demo',
    'demo.howItWorks': 'How It Works',
    'demo.stepByStep': 'Step by step process',
    'demo.testimonials': 'What our users say',
    'demo.cta.title': 'Ready to transform your career?',
    'demo.cta.desc': 'Join thousands of professionals already using NexusAI',
    'demo.cta.start': 'Start Free',
    'demo.cta.learn': 'Learn More',
    'demo.resume.title': 'Resume Optimization',
    'demo.resume.desc': 'See how AI analyzes and improves your resume in real time',
    'demo.resume.step1': 'Upload your current resume',
    'demo.resume.step2': 'Automatic analysis of strengths and weaknesses',
    'demo.resume.step3': 'AI-based improvement suggestions',
    'demo.resume.step4': 'Generate optimized resume in PDF',
    'demo.resume.stat1': 'Average increase in response rate',
    'demo.resume.stat2': 'Average optimization time',
    'demo.resume.stat3': 'Optimized resumes',
    'demo.interview.title': 'Interview Preparation',
    'demo.interview.desc': 'Practice with realistic interview simulations',
    'demo.interview.step1': 'Choose the desired job type',
    'demo.interview.step2': 'Receive personalized questions',
    'demo.interview.step3': 'Record your answers in real time',
    'demo.interview.step4': 'Get detailed AI feedback',
    'demo.interview.stat1': 'Approval rate after training',
    'demo.interview.stat2': 'Available questions',
    'demo.interview.stat3': 'Personalized feedback',
    'demo.skills.title': 'Skills Development',
    'demo.skills.desc': 'Improve your skills with personalized tracks',
    'demo.skills.step1': 'Initial skills assessment',
    'demo.skills.step2': 'Personalized learning path',
    'demo.skills.step3': 'Practical exercises and challenges',
    'demo.skills.step4': 'Completion certificates',
    'demo.skills.stat1': 'Available skills',
    'demo.skills.stat2': 'Average completion time',
    'demo.skills.stat3': 'Satisfaction rate',
  },
  es: {
    'nav.features': 'Características',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'auth.login': 'Iniciar sesión',
    'auth.signup': 'Registrarse',
    'auth.logout': 'Cerrar sesión',
    'nav.dashboard': 'Panel',
    'hero.badge': 'Orientación Profesional con IA',
    'hero.title': 'Tu viaje hacia el',
    'hero.titleHighlight': ' mercado laboral ',
    'hero.titleEnd': 'comienza aquí',
    'hero.description': 'NexusAI es tu asistente inteligente para encontrar oportunidades, mejorar tu currículum y conseguir el trabajo de tus sueños.',
    'hero.getStarted': 'Comenzar Ahora',
    'hero.demo': 'Ver Demostración',
    'hero.stat1': 'Jóvenes Orientados',
    'hero.stat2': 'Tasa de Éxito',
    'hero.stat3': 'Soporte IA',
    'features.title': 'Recursos que',
    'features.titleHighlight': ' Transforman',
    'features.titleEnd': ' Carreras',
    'features.subtitle': 'Descubre cómo nuestra inteligencia artificial puede acelerar tu entrada al mercado laboral',
    'features.resume.title': 'Optimización de Currículum',
    'features.resume.desc': 'La IA analiza y optimiza tu currículum para cada vacante específica, destacando tus mejores cualidades.',
    'features.resume.action': 'Optimizar Currículum',
    'features.interview.title': 'Preparación para Entrevistas',
    'features.interview.desc': 'Simulaciones de entrevistas personalizadas con retroalimentación inteligente para destacarte.',
    'features.interview.action': 'Entrenar Entrevistas',
    'features.jobs.title': 'Búsqueda Inteligente de Empleos',
    'features.jobs.desc': 'Encuentra oportunidades perfectas basadas en tu perfil, experiencia y objetivos profesionales.',
    'features.jobs.action': 'Buscar Empleos',
    'features.skills.title': 'Desarrollo de Habilidades',
    'features.skills.desc': 'Identifica brechas de competencias y recibe un plan personalizado de capacitación.',
    'features.skills.action': 'Desarrollar Habilidades',
    'features.networking.title': 'Networking Estratégico',
    'features.networking.desc': 'Conecta con profesionales de tu área y expande tu red de contactos.',
    'features.networking.action': 'Hacer Networking',
    'features.mentoring.title': 'Orientación Personalizada',
    'features.mentoring.desc': 'Mentoría 24/7 con IA que entiende tus objetivos y traza el mejor camino profesional.',
    'features.mentoring.action': 'Obtener Orientación',
    'features.cta': 'Probar Todas las Funciones',
    'about.title': 'Por qué elegir',
    'about.titleHighlight': ' NexusAI',
    'about.subtitle': 'Desarrollamos una plataforma diseñada específicamente para jóvenes brasileños que están dando sus primeros pasos en el mercado laboral.',
    'about.data.title': 'Orientación Basada en Datos',
    'about.data.desc': 'Nuestra IA analiza miles de vacantes y perfiles profesionales para ofrecer consejos precisos y actualizados con el mercado.',
    'about.focus.title': 'Enfoque en el Primer Empleo',
    'about.focus.desc': 'Entendemos los desafíos únicos de quienes están comenzando y adaptamos nuestras estrategias para superar estas barreras.',
    'about.learning.title': 'Aprendizaje Continuo',
    'about.learning.desc': 'Sigue las tendencias del mercado y desarrolla las habilidades más buscadas por los empleadores.',
    'about.support.title': 'Soporte Humanizado',
    'about.support.desc': 'Tecnología avanzada con toque humano. Nuestra IA está entrenada para ser empática y comprender tus necesidades individuales.',
    'about.stat1': 'Currículums optimizados',
    'about.stat2': 'Tasa de aprobación en procesos',
    'about.cta': 'Comienza Tu Viaje Profesional',
    'contact.title': 'Ponte en',
    'contact.titleHighlight': ' Contacto',
    'contact.subtitle': '¿Tienes alguna pregunta o necesitas ayuda? ¡Nuestro equipo está listo para orientarte!',
    'contact.info': 'Contáctanos',
    'contact.email': 'Correo Electrónico',
    'contact.phone': 'Teléfono',
    'contact.address': 'Dirección',
    'contact.form.title': 'Enviar un Mensaje',
    'contact.form.name': 'Nombre',
    'contact.form.namePlaceholder': 'Tu nombre',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.emailPlaceholder': 'tu@email.com',
    'contact.form.subject': 'Asunto',
    'contact.form.subjectPlaceholder': '¿Cómo podemos ayudarte?',
    'contact.form.message': 'Mensaje',
    'contact.form.messagePlaceholder': 'Describe tu pregunta o sugerencia...',
    'contact.form.submit': 'Enviar Mensaje',
    'dashboard.title': 'Panel de Control',
    'dashboard.welcome': 'Bienvenido de nuevo',
    'dashboard.welcomeBack': 'Bienvenido de nuevo',
    'dashboard.resume': 'Optimizar Currículum',
    'dashboard.resumeDesc': 'Crea y optimiza tu currículum profesional',
    'dashboard.interview': 'Preparación para Entrevistas',
    'dashboard.interviewDesc': 'Practica y prepárate para tus entrevistas',
    'dashboard.skills': 'Desarrollo de Habilidades',
    'dashboard.skillsDesc': 'Mejora tus competencias profesionales',
    'dashboard.jobs': 'Buscar Empleos',
    'dashboard.jobsDesc': 'Encuentra oportunidades de empleo',
    'dashboard.backHome': 'Volver al Inicio',
    'dashboard.home': 'Inicio',
    'dashboard.settings': 'Configuración',
    'dashboard.admin': 'Panel Admin',
    'dashboard.errorProfile': 'Error al cargar perfil',
    'dashboard.errorPermissions': 'Error al verificar permisos',
    'dashboard.quickActions': 'Acciones Rápidas',
    'dashboard.recentActivity': 'Actividad Reciente',
    'dashboard.recommendations': 'Recomendaciones para Ti',
    'dashboard.profileStrength': 'Fortaleza del Perfil',
    'dashboard.aiInsights': 'Perspectivas de IA',
    'settings.title': 'Configuración',
    'settings.description': 'Administra tus preferencias e información personal',
    'settings.profileCompletion': 'Completitud del Perfil',
    'settings.completeYourProfile': 'Completa tu perfil para mejorar tu experiencia',
    'settings.complete': 'completo',
    'settings.fields': 'campos',
    'settings.suggestions': 'Sugerencias',
    'settings.add': 'Agregar',
    'settings.careerField': 'Campo Profesional',
    'settings.experienceLevel': 'Nivel de Experiencia',
    'settings.avatarUrl': 'Foto de Perfil',
    'settings.profile': 'Perfil',
    'settings.notifications': 'Notificaciones',
    'settings.privacy': 'Privacidad',
    'settings.security': 'Seguridad',
    'settings.appearance': 'Apariencia',
    'settings.personalInfo': 'Información Personal',
    'settings.fullName': 'Nombre Completo',
    'settings.email': 'Correo Electrónico',
    'settings.phone': 'Teléfono',
    'settings.bio': 'Biografía',
    'settings.bioPlaceholder': 'Cuéntanos sobre ti...',
    'settings.saveProfile': 'Guardar Perfil',
    'settings.profileUpdated': '¡Perfil actualizado!',
    'settings.profileUpdateDesc': 'Tu información ha sido guardada exitosamente.',
    'settings.notificationPrefs': 'Preferencias de Notificación',
    'settings.emailNotifications': 'Notificaciones por Correo',
    'settings.emailNotificationsDesc': 'Recibe notificaciones importantes por correo',
    'settings.pushNotifications': 'Notificaciones Push',
    'settings.pushNotificationsDesc': 'Recibe notificaciones en tiempo real',
    'settings.weeklyReport': 'Informe Semanal',
    'settings.weeklyReportDesc': 'Recibe un resumen de tus actividades',
    'settings.courseUpdates': 'Actualizaciones de Cursos',
    'settings.courseUpdatesDesc': 'Nuevos cursos y materiales disponibles',
    'settings.saveNotifications': 'Guardar Notificaciones',
    'settings.notificationsSaved': '¡Preferencias guardadas!',
    'settings.notificationsSavedDesc': 'Tu configuración de notificación ha sido actualizada.',
    'settings.privacySettings': 'Configuración de Privacidad',
    'settings.profileVisibility': 'Visibilidad del Perfil',
    'settings.public': 'Público',
    'settings.private': 'Privado',
    'settings.showEmail': 'Mostrar Correo',
    'settings.showEmailDesc': 'Tu correo será visible en tu perfil',
    'settings.showPhone': 'Mostrar Teléfono',
    'settings.showPhoneDesc': 'Tu teléfono será visible en tu perfil',
    'settings.savePrivacy': 'Guardar Privacidad',
    'settings.privacyUpdated': '¡Privacidad actualizada!',
    'settings.privacyUpdatedDesc': 'Tu configuración de privacidad ha sido guardada.',
    'settings.twoFactor': 'Autenticación de Dos Factores (2FA)',
    'settings.twoFactorDesc': 'Agrega una capa extra de seguridad a tu cuenta',
    'settings.twoFactorEnabled': '2FA está activado',
    'settings.twoFactorDisabled': '2FA está desactivado',
    'settings.enable2FA': 'Activar 2FA',
    'settings.disable2FA': 'Desactivar 2FA',
    'settings.2FADisabled': '2FA Desactivado',
    'settings.2FADisabledDesc': 'Autenticación de dos factores ha sido desactivada',
    'settings.error2FA': 'Fallo al desactivar 2FA',
    'settings.themeSettings': 'Configuración de Tema',
    'settings.currentTheme': 'Tema Actual',
    'settings.themeToggle': 'Cambiar Tema',
    'profile.dashboard': 'Panel',
    'profile.settings': 'Configuración',
    'profile.logout': 'Cerrar Sesión',
    'profile.professional': 'Profesional',
    'admin.title': 'Panel de Administración',
    'admin.description': 'Gestionar usuarios y permisos',
    'admin.authSettings': 'Configuración de Autenticación',
    'admin.authSettingsDesc': 'Gestionar configuración de autenticación y registro',
    'admin.requireEmailConfirmation': 'Requerir confirmación de correo',
    'admin.emailConfirmationDesc': 'Los usuarios deben confirmar el correo antes de iniciar sesión (deshabilitar para pruebas)',
    'admin.settingsSaved': 'Configuración guardada',
    'admin.emailConfirmationEnabled': 'Confirmación de correo habilitada',
    'admin.emailConfirmationDisabled': 'Confirmación de correo deshabilitada (modo desarrollo)',
    'admin.error': 'Error',
    'admin.errorSavingSettings': 'Error al guardar configuración',
    'admin.allUsers': 'Todos los Usuarios',
    'admin.name': 'Nombre',
    'admin.email': 'Correo',
    'admin.role': 'Rol',
    'admin.createdAt': 'Creado en',
    'admin.actions': 'Acciones',
    'admin.noUsers': 'No se encontraron usuarios',
    'admin.deleteUser': 'Eliminar Usuario',
    'admin.deleteConfirm': '¿Estás seguro de que deseas eliminar este usuario?',
    'admin.deleteDesc': 'Esta acción no se puede deshacer.',
    'admin.cancel': 'Cancelar',
    'admin.delete': 'Eliminar',
    'admin.userDeleted': 'Usuario eliminado',
    'admin.userDeletedDesc': 'El usuario ha sido eliminado exitosamente',
    'admin.errorDelete': 'Error al eliminar usuario',
    'admin.errorFetch': 'Error al cargar usuarios',
    'admin.admin': 'Admin',
    'admin.client': 'Cliente',
    'demo.title': 'NexusAI Demo',
    'demo.hero': 'Explora el Poder de',
    'demo.heroHighlight': ' la IA ',
    'demo.heroEnd': 'en tu desarrollo profesional',
    'demo.heroDesc': 'Ve demostraciones interactivas de cómo NexusAI puede transformar tu carrera',
    'demo.watchDemo': 'Ver Demo',
    'demo.howItWorks': 'Cómo Funciona',
    'demo.stepByStep': 'Proceso paso a paso',
    'demo.testimonials': 'Lo que dicen nuestros usuarios',
    'demo.cta.title': '¿Listo para transformar tu carrera?',
    'demo.cta.desc': 'Únete a miles de profesionales que ya usan NexusAI',
    'demo.cta.start': 'Comenzar Gratis',
    'demo.cta.learn': 'Saber Más',
    'demo.resume.title': 'Optimización de Currículum',
    'demo.resume.desc': 'Ve cómo la IA analiza y mejora tu currículum en tiempo real',
    'demo.resume.step1': 'Sube tu currículum actual',
    'demo.resume.step2': 'Análisis automático de fortalezas y debilidades',
    'demo.resume.step3': 'Sugerencias de mejora basadas en IA',
    'demo.resume.step4': 'Generación de currículum optimizado en PDF',
    'demo.resume.stat1': 'Aumento promedio en tasa de respuesta',
    'demo.resume.stat2': 'Tiempo promedio de optimización',
    'demo.resume.stat3': 'Currículums optimizados',
    'demo.interview.title': 'Preparación para Entrevistas',
    'demo.interview.desc': 'Practica con simulaciones realistas de entrevistas',
    'demo.interview.step1': 'Elige el tipo de puesto deseado',
    'demo.interview.step2': 'Recibe preguntas personalizadas',
    'demo.interview.step3': 'Graba tus respuestas en tiempo real',
    'demo.interview.step4': 'Obtén retroalimentación detallada de la IA',
    'demo.interview.stat1': 'Tasa de aprobación después del entrenamiento',
    'demo.interview.stat2': 'Preguntas disponibles',
    'demo.interview.stat3': 'Retroalimentación personalizada',
    'demo.skills.title': 'Desarrollo de Habilidades',
    'demo.skills.desc': 'Mejora tus competencias con rutas personalizadas',
    'demo.skills.step1': 'Evaluación inicial de competencias',
    'demo.skills.step2': 'Ruta de aprendizaje personalizada',
    'demo.skills.step3': 'Ejercicios prácticos y desafíos',
    'demo.skills.step4': 'Certificados de finalización',
    'demo.skills.stat1': 'Habilidades disponibles',
    'demo.skills.stat2': 'Tiempo promedio de finalización',
    'demo.skills.stat3': 'Tasa de satisfacción',
  },
  fr: {},
  de: {},
  it: {},
  zh: {},
  ja: {},
  ko: {},
  ru: {},
  ar: {},
  hi: {},
};

// Add minimal translations for other languages to avoid errors
const minimalTranslations = {
  'nav.features': 'Features',
  'nav.about': 'About',
  'nav.contact': 'Contact',
  'auth.login': 'Login',
  'auth.signup': 'Sign Up',
  'auth.logout': 'Logout',
  'nav.dashboard': 'Dashboard',
  'hero.badge': 'AI Career Guidance',
  'hero.title': 'Your journey to',
  'hero.titleHighlight': ' job market ',
  'hero.titleEnd': 'starts here',
  'hero.description': 'NexusAI is your intelligent career assistant.',
  'hero.getStarted': 'Get Started',
  'hero.demo': 'View Demo',
};

// Fill in remaining languages with minimal translations
['fr', 'de', 'it', 'zh', 'ja', 'ko', 'ru', 'ar', 'hi'].forEach(lang => {
  if (Object.keys(translations[lang as Language]).length === 0) {
    translations[lang as Language] = minimalTranslations;
  }
});

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('pt');
  const [userId, setUserId] = useState<string | null>(null);

  // Load language preference from database or localStorage
  useEffect(() => {
    const loadLanguage = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      
      if (session?.user) {
        setUserId(session.user.id);
        // Load from database for authenticated users
        const { data } = await supabase
          .from('profiles')
          .select('preferred_language')
          .eq('user_id', session.user.id)
          .single();
        
        if (data?.preferred_language) {
          setLanguageState(data.preferred_language as Language);
          document.documentElement.dir = data.preferred_language === 'ar' ? 'rtl' : 'ltr';
          document.documentElement.lang = data.preferred_language;
        }
      } else {
        // Load from localStorage for non-authenticated users
        const savedLanguage = localStorage.getItem('language') as Language;
        if (savedLanguage) {
          setLanguageState(savedLanguage);
          document.documentElement.dir = savedLanguage === 'ar' ? 'rtl' : 'ltr';
          document.documentElement.lang = savedLanguage;
        }
      }
    };
    
    loadLanguage();

    // Listen for auth changes
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (session?.user) {
        setUserId(session.user.id);
        loadLanguage();
      } else {
        setUserId(null);
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    
    // Update document direction for RTL languages
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    
    // Save to database if user is authenticated
    if (userId) {
      await supabase
        .from('profiles')
        .update({ preferred_language: lang })
        .eq('user_id', userId);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en?.[key] || translations.pt?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
